function [boutData] = computeFoodBouts(foodVector, framerate)
% computeFoodBouts Converts a logical vector indicating whether an animals
% was on or off food to "Bout" format. Each bout is a 2 column vector with
% the starting and ending frame for the bout. 
%   
%
% Inputs:
%   foodVector: a vector marking frames within food patches (1) or outside
%   food patches (0). This can be generated by running the drawPatchROI
%   script.
%    
%    framerate (optional): frames per second of recording. Can be left
%    blank, or can be a scalar value indicating framerate. Or if plot
%    settings are passed, the framerate will be extracted from the settings
%    structure.
%
% Outputs:
%   boutData: a structure with the following fields
%       onFood - an M by 2 matrix with each row representing an on-food
%       bout. The first column indicates the frame a worm entered food, the
%       second the frame it left food.
%       
%       offFood - same as on food, but for off-food bouts. 
%        
%       onDuration - time spent on-food for each bout.
%
%       offDuration - time spent off-food for each bout.
%
%       xPatch - x coordinates for plotting patches. Units are in frames,
%       so convert to correct time units when plotting. 
%
%       yPatch - arbitrary [0 1] y coordinates for plotting patches.
%       multiply by the maximum value of your data or axis to get correct
%       range. 
if nargin<1
    wormdata = evalin('caller', 'wormdata');
    foodVector = wormdata.onFoodVector;
    fps = 15;
elseif nargin<2
    fps = 15;
elseif isscalar(framerate)
    fps = framerate;
elseif isstruct(framerate)
    fps = framerate.framerate;
end

onFood = [];
offFood = [];

%% find whether the worm starts on or off food
switch foodVector(1) 
    case 1
        onFood(1) = 1;
    case 0
        offFood(1) = 1;
end

%% find transition points in the foodVector (1 marks on food, 0 off food)
dif = diff(foodVector); % determine transitions by subracting the previous value, 0 = no change
off = find(dif==-1); % -1 is a leaving event
on = find(dif==1); % +1 is an entry event

%% concatenate the starting state
onFood = vertcat(onFood, on);
offFood = vertcat(offFood, off);


%% compute 'on food' bouts (beginning and end frames)
onBouts = nan(length(onFood),2);
onDuration = nan(length(offFood),1);

for i =1:length(onFood)
    thisOn = onFood(i);
    onBouts(i,1) = thisOn;

    % find the subsequent leaving event
    thisOff = find(offFood>thisOn, 1, "first");

    if ~isempty(thisOff) % make sure its not the last timepoint
        onBouts(i,2) = offFood(thisOff);
    else
        onBouts(i,2) = length(foodVector);
    end

    onDuration(i) = (onBouts(i,2)-onBouts(i,1))/fps/60;
end


%% compute 'off food' bouts (beginning and end frames)
offBouts = nan(length(offFood),2);
offDuration = nan(length(offFood),1);

for i =1:length(offFood)
    thisOff = offFood(i);
    offBouts(i,1) = thisOff; 

    % find the subsequent entry event
    thisOn = find(onFood>thisOff, 1, "first"); 
    if ~isempty(thisOn) % make sure its not the last timepoint
        offBouts(i,2) = onFood(thisOn);
    else
        offBouts(i,2) = length(foodVector);
    end

    offDuration(i) = (offBouts(i,2)-offBouts(i,1))/fps/60;
end

%% Create onFood X coordinates for plotting patches, units are frames.
xpatch = nan(4,length(onBouts));
for i=1:length(onBouts)
    s = onBouts(i,1);
    e = onBouts(i,2);
    xpatch(1:4, i) = [s s e e];
end

%% Create arbitrary [0 1] Y coordinates for the patches.
ypatch = repmat([0; 1; 1; 0],1 ,length(onFood));


%% Compile data
boutData.onFood = onBouts;
boutData.offFood = offBouts;
boutData.onDuration = onDuration;
boutData.offDuration = offDuration;
boutData.xPatch = xpatch;
boutData.yPatch = ypatch;

end
% if nargin < 4 || isempty(yRange)
%     yRange = [0 1];
% end
% 
% % make column vectors and ensure sorted & unique (defensive)
% onFood  = unique(sort(onFood(:)));
% offFood = unique(sort(offFood(:)));
% 
% % --- build onBouts by pairing each onStart with first off > onStart
% if isempty(onFood)
%     onBouts = zeros(0,2);
%     onDur   = zeros(0,1);
%     onPatches = struct('x',{},'y',{});
% else
%     nOn = numel(onFood);
%     onStart = onFood;
%     onEnd = zeros(nOn,1);
%     for i = 1:nOn
%         idx = find(offFood > onStart(i), 1, 'first');
%         if ~isempty(idx)
%             onEnd(i) = offFood(idx);
%         else
%             onEnd(i) = totalFrames;   % no off after this on => runs to end
%         end
%     end
%     % remove any zero-length or reversed bouts (defensive)
%     valid = onEnd > onStart;
%     onBouts = [onStart(valid) onEnd(valid)];
%     onDur = onBouts(:,2) - onBouts(:,1);
% end
% 
% % --- build offBouts by pairing each offStart with first on > offStart
% % include initial off bout that starts at 1
% offStartCandidates = [1; offFood];
% nOff = numel(offStartCandidates);
% offEnd = zeros(nOff,1);
% for i = 1:nOff
%     s = offStartCandidates(i);
%     idx = find(onFood > s, 1, 'first');
%     if ~isempty(idx)
%         offEnd(i) = onFood(idx);
%     else
%         offEnd(i) = totalFrames;
%     end
% end
% validOff = offEnd > offStartCandidates;
% offBouts = [offStartCandidates(validOff) offEnd(validOff)];
% offDur = offBouts(:,2) - offBouts(:,1);
% 
% boutData.onBouts = onBouts;
% boutData.offBouts = offBouts;
% boutData.onDur = onDur;
% boutData.offDur = offDur; 
% 
% for k = 1:size(onBouts,1)
%     s = onBouts(k,1); e = onBouts(k,2);
%     boutData.patchX(1:4, k) = [s e e s];
%     boutData.patchY(1:4, k) = [yRange(1) yRange(1) yRange(2) yRange(2)];
% end
% end